### ISSUE TITLE
switch default openai to gpt4 

### ISSUE THREAD

**Issue by blankenshipz** [gsuuon/model.nvim#43]
For most of my use cases I'm okay with the "starter" prompts (and in fact just the default prompt); however I'd love it if I could switch the default gpt-3.5-turbo to a gpt4 model - is there an easy way to just override this setting?

**Comment by gsuuon** [comment]
There is! You can override the default params for the openai provider:
```lua
    config = function()
      require('model.providers.openai').initialize({
        model = 'gpt-4-1106-preview'
      })
    end
```
I thought this was in the docs, I'll add it now.
